const CSS_DATA_URL_PREFIX = "data:text/css";
const PROPERTIES_LAYER_AT_RULE = "@layer properties";
const SUPPORTS_AT_RULE = "@supports";

function findBlockEnd(stylesheet: string, blockStart: number): number {
	let depth = 0;

	for (let index = blockStart; index < stylesheet.length; index += 1) {
		const character = stylesheet[index];

		if (character === "{") {
			depth += 1;
		} else if (character === "}") {
			depth -= 1;

			if (depth === 0) {
				return index;
			}
		}
	}

	return -1;
}

function skipWhitespace(stylesheet: string, index: number): number {
	let cursor = index;

	while (cursor < stylesheet.length && /\s/.test(stylesheet[cursor] ?? "")) {
		cursor += 1;
	}

	return cursor;
}

/**
 * Locates the `@layer properties { ... }` block. Tailwind also emits a bare
 * `@layer properties;` ordering statement, and the block itself appears at the
 * top in minified output but at the end in development output, so match on the
 * following `{` rather than on a fixed offset.
 */
function findPropertiesLayerBlock(
	stylesheet: string,
): { start: number; bodyStart: number; bodyEnd: number } | undefined {
	let searchFrom = 0;

	while (true) {
		const start = stylesheet.indexOf(PROPERTIES_LAYER_AT_RULE, searchFrom);

		if (start === -1) {
			return undefined;
		}

		const bodyStart = skipWhitespace(
			stylesheet,
			start + PROPERTIES_LAYER_AT_RULE.length,
		);

		if (stylesheet[bodyStart] === "{") {
			const bodyEnd = findBlockEnd(stylesheet, bodyStart);

			if (bodyEnd !== -1) {
				return { start, bodyStart, bodyEnd };
			}
		}

		searchFrom = start + PROPERTIES_LAYER_AT_RULE.length;
	}
}

/**
 * Tailwind registers its internal `--tw-*` custom properties with `@property`
 * and only emits plain fallback declarations behind an `@supports` guard for
 * engines without `@property`. `@property` is document-scoped, so the rules in
 * a `ShadowRoot` stylesheet are ignored: every `--tw-*` reference resolves to
 * the guaranteed-invalid value and the `border`, `ring`, `shadow`, and
 * `transform` utilities silently drop out of the control panel.
 *
 * Registering the properties on the GitLab document would repair the shadow
 * tree by mutating the host page, and GitLab.com already ships unregistered
 * Tailwind v3 `--tw-*` variables that such a registration would redefine.
 * Unwrapping the `@supports` guard instead keeps the fallback declarations
 * inside the owned shadow tree, where `*` matches nothing in GitLab's light
 * DOM, and keeps the declaration list generated by Tailwind rather than
 * hand-maintained.
 *
 * This scans text rather than walking CSSOM on purpose. Happy DOM, which backs
 * the test layer, drops `@layer` blocks entirely on `replaceSync` and exposes
 * no `CSSLayerBlockRule`, so a CSSOM implementation would be untestable here
 * and silently wrong under test. The tradeoff is that the scanner is unaware of
 * strings and comments; Tailwind's output contains no brace inside either.
 */
export function applyShadowRootPropertyFallback(stylesheet: string): string {
	const layer = findPropertiesLayerBlock(stylesheet);

	if (!layer) {
		throw new Error(
			"Expected a Tailwind @layer properties block in the bundled control-panel CSS",
		);
	}

	const layerBody = stylesheet.slice(layer.bodyStart + 1, layer.bodyEnd);
	const supportsStart = layerBody.indexOf(SUPPORTS_AT_RULE);

	if (supportsStart === -1) {
		throw new Error(
			"Expected an @supports fallback inside the Tailwind @layer properties block",
		);
	}

	const supportsBodyStart = layerBody.indexOf("{", supportsStart);
	const supportsBodyEnd =
		supportsBodyStart === -1 ? -1 : findBlockEnd(layerBody, supportsBodyStart);

	if (supportsBodyEnd === -1) {
		throw new Error(
			"Could not unwrap the @supports fallback in the bundled control-panel CSS",
		);
	}

	const unguardedBody = `${layerBody.slice(0, supportsStart)}${layerBody.slice(
		supportsBodyStart + 1,
		supportsBodyEnd,
	)}${layerBody.slice(supportsBodyEnd + 1)}`;

	return `${stylesheet.slice(0, layer.start)}${PROPERTIES_LAYER_AT_RULE}{${unguardedBody}}${stylesheet.slice(layer.bodyEnd + 1)}`;
}

/**
 * Both data-URL encodings the bundler has emitted are accepted.
 *
 * Extension.js inlined this stylesheet as `data:text/css;base64,...` up to
 * 4.0.32 and switched to `data:text/css;charset=utf-8,` with an
 * `encodeURIComponent` payload in 4.1.14. Insisting on base64 turned a bundler
 * detail into a shipped defect: the decode threw, the control panel reported
 * itself unavailable, and no unit test noticed because the test built the data
 * URL itself. The value never crosses a trust boundary, it is produced by our
 * own build, so reading whichever encoding the build emits is the contract that
 * matters.
 */
export function decodeBundledStylesheet(stylesheetUrl: string): string {
	const payloadStart = stylesheetUrl.indexOf(",");

	if (!stylesheetUrl.startsWith(CSS_DATA_URL_PREFIX) || payloadStart === -1) {
		throw new Error("Expected the bundled control-panel CSS as a data URL");
	}

	const parameters = stylesheetUrl.slice(
		CSS_DATA_URL_PREFIX.length,
		payloadStart,
	);
	const payload = stylesheetUrl.slice(payloadStart + 1);
	const stylesheet = parameters.split(";").includes("base64")
		? new TextDecoder().decode(
				Uint8Array.from(atob(payload), (character) => character.charCodeAt(0)),
			)
		: decodeURIComponent(payload);

	return applyShadowRootPropertyFallback(stylesheet);
}
